### ISSUE TITLE
Feature request -- instructions for hooking it in to Teensy?

### ISSUE THREAD

**Issue by nimishgautam** [joakim/doomsday-device#2]
Could you possibly include instructions on how to physically wire it to Teensy as well, for those of us who are better with software than hardware?

(these are available online again from thinkgeek)

**Comment by joakim** [comment]
Sorry for the embarrassingly late reply!

It's pretty straight forward if you know how to solder, no more difficult than soldering an LED for example. I'd check out [Adafruit's guide to excellent soldering](https://learn.adafruit.com/adafruit-guide-excellent-soldering/tools). It's best to train on something that won't break your heart if you mess up. I can also recommend going to a hackerspace if you have one nearby. Best of luck :)
